name: Setup clash
description: convert subscription url & run clash in backgroud
branding:
  icon: cloud
  color: white
inputs:
  subscription_url:
    description: 'subscribption url'
    required: true
  proxies_name_regex:
    description: 'regex for proxies'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: download subscribe2clash
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        curl -L https://github.com/whoisix/subscribe2clash/releases/download/v1.0.3/subscribe2clash-linux-amd64-v1.0.3.gz -o subscribe2clash.gz
        gzip -d subscribe2clash.gz
        chmod +x subscribe2clash
        nohup ./subscribe2clash -l 127.0.0.1:8162 -b ${{ github.action_path }}/base_conf.yml &
    - name: download clash
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        curl -L https://github.com/Dreamacro/clash/releases/download/v1.10.0/clash-linux-amd64-v1.10.0.gz -o clash.gz
        gzip -d clash.gz
        chmod +x clash
    - name: download Deno
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        curl -L https://github.com/denoland/deno/releases/download/v1.21.1/deno-x86_64-unknown-linux-gnu.zip -o deno.zip
        unzip deno.zip
        chmod +x deno
    - name: run clash and choose first proxy
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        curl "127.0.0.1:8162?sub_link=${{ inputs.subscription_url }}" > clash.yml
        ./deno run -A ${{ github.action_path }}/doFilter.js ${{ inputs.proxies_name_regex }}
        nohup ./clash -f ${{ github.action_path }}/clash_filtered.yml &
        sleep 5
        curl -X PUT "127.0.0.1:9090/proxies/GLOBAL" -d '{"name": "1"}'
        curl --proxy "http://127.0.0.1:11223" ipinfo.io
    