name: Setup clash
description: convert subscription url & run clash in backgroud
branding:
  icon: cloud
  color: white
inputs:
  subscription_url:
    description: 'subscribption url'
    required: true
  proxies_name_regex:
    description: 'regex for proxies'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: download subscribe2clash
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        curl -L https://github.com/tindy2013/subconverter/releases/download/v0.9.0/subconverter_linux64.tar.gz -o subconverter.tgz
        tar -xzf subconverter.tgz
        nohup ./subconverter/subconverter &
    - name: download clash
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        curl -L https://github.com/MetaCubeX/mihomo/releases/download/v1.18.7/mihomo-linux-amd64-v1.18.7.gz -o clash.gz
        gzip -d clash.gz
        chmod +x clash
    - name: download Deno
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        curl -L https://github.com/denoland/deno/releases/download/v1.45.5/deno-x86_64-unknown-linux-gnu.zip -o deno.zip
        unzip deno.zip
        chmod +x deno
    - name: run clash and choose first proxy
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        curl --get "127.0.0.1:25500/sub" --data-urlencode "target=clash" --data-urlencode "url=${{ inputs.subscription_url }}" > clash.yml
        ./deno run --allow-read --allow-write ${{ github.action_path }}/proxyFilter.js ${{ inputs.proxies_name_regex }}
        nohup ./clash -f ${{ github.action_path }}/clash_filtered.yml &
        sleep 5
        curl -X PATCH "127.0.0.1:9090/configs" -d '{"mode": "global"}'
    
